-- npx wrangler d1 execute preview-104-baufak --remote --file=functions/schema.sql

CREATE TABLE IF NOT EXISTS registrations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  vorname TEXT,
  nachname TEXT,
  email TEXT,
  telefon TEXT,
  hochschule TEXT,
  statusGruppe TEXT,
  ersteBaufak INTEGER,
  wievielteBaufak INTEGER,
  bauhelm INTEGER,
  sicherheitsschuhe INTEGER,
  deutschlandticket INTEGER,
  anreisezeitpunkt TEXT,
  anreisezeitpunktKommentar TEXT,
  anreisemittel TEXT,
  abreisezeitpunkt TEXT,
  abreisezeitpunktKommentar TEXT,
  abreisemittel TEXT,
  schlafplatz INTEGER,
  kommentarSchlafplatz TEXT,
  schlafplatzAuswahl TEXT,
  schlafplatzPersonen TEXT,
  ernaehrung TEXT,
  allergieLaktose INTEGER,
  allergieUniversitaet INTEGER,
  allergieGluten INTEGER,
  allergieNuesse INTEGER,
  allergieArchitekten INTEGER,
  allergieSoja INTEGER,
  allergien TEXT,
  tshirt TEXT,
  buddy TEXT,
  kommentar TEXT,
  datenschutz INTEGER,
  teilnahmegebuehr INTEGER,
  immatbescheinigungId TEXT
);